---
apiVersion: v1
kind: Service
metadata:
  name: drupal 
  labels:
    app: drupal
spec:
  ports:
    - port: 80
      name: web
      targetPort: 80
  selector:
    app: drupal
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
  labels:
    app: drupal
spec:
  storageClassName: "oci-bv"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
    tier: frontend
spec:
  selector:
    matchLabels:
      app: drupal
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      initContainers:
        - name: init-sites-volume
          image: drupal:latest
          command: ['/bin/bash', '-c']
          args: ['cp -r /var/www/html/sites /data; chown www-data:www-data /data/ -R']
          volumeMounts:
          - mountPath: /data
            name: drupal-pvc
      containers:
      - image: drupal:latest
        imagePullPolicy: IfNotPresent
        name: drupal
        env:
        - name: DRUPAL_DATABASE_HOST
          value: drupal-mysql
        - name: DRUPAL_DATABASE_PASSWORD
          value: Tisal2020
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-pvc
          mountPath: /var/www/html/modules
          subPath: modules
        - name: drupal-pvc
          mountPath: /var/www/html/profiles
          subPath: profiles
        - name: drupal-pvc
          mountPath: /var/www/html/sites
          subPath: sites
        - name: drupal-pvc
          mountPath: /var/www/html/themes
          subPath: themes
      volumes:
        - name: drupal-pvc
          persistentVolumeClaim:
            claimName: drupal-pvc